apiVersion: apps/v1
kind: Deployment
metadata:
  name: flipkart-app-deployment
  labels:
    first: flipkart
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flip
  template:
    metadata:
      labels:
        app: flip
    spec:
      containers:
        - name: flipkart-cont
          image: anushanayak091/flipkart-app-web:v1.0.0
          ports:
            - containerPort: 80