apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
spec:
  containers:
    -  name: grocery-app
       image: anushanayak091/turbo-grocery-app:V4.3.0
       ports:
        -  containerPort: 80
    -  name: sample-cont
       image: anushanayak091/anusha-priya:1.0.0
       ports:
        -  containerPort: 3015