apiVersion: v1
kind: Pod
metadata:
  name: flipkart-pod
  namespace: test-ns
spec:
  containers:
    - name: flip-cont
      image: anushanayak091/flipkart-app-web:v1.0.0
      ports:
        -  containerPort: 80