apiVersion: apps/v1 
kind: ReplicaSet 
metadata: 
  name: grocery-app-rs 
  labels:
    app: web
spec: # Defines the Behaviour of the replicaset 
  replicas: 3 
  selector:
    matchLabels:
      web: grocery
  template:
    metadata:
      labels:
        web: grocery 
    spec: # Defines the Behaviour of the Pod 
      containers:
        - image: anushanayak091/turbo-grocery-app:V4.3.0
          name: turbo-cont
          ports:
            - containerPort: 80