apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: grocery-app-rs
  labels:
    app: web
spec: #Defines the behaviour of the replicaset
  replicas: 3
  selector:
    matchLables:
      web: grocery
  template:
    metadata:
      labels: 
        web: grocery
    spec: #Defines the behaviour of the Pod
      containers: 
        -  image: anushanayak091/turbo-grocery-app:V4.3.0
           name: sre-web
           ports:
            -  containerPort: 80